### ISSUE TITLE
6.0 disk drive file issue

### ISSUE THREAD

**Issue by williamb64** [exelix11/SwitchThemeInjector#1]
none of the files for 6.0 theme files on the disk drive show up

**Comment by jaconfurz** [comment]
> none of the files for 6.0 theme files on the disk drive show up

Mine was the same way, it is very weird. I noticed my folder names match those as users on Japan switches. Here is my Qlaunch NCA "33dd03103f1ac6a50e13d27ce5e00b2f.nca", see if you have that in your disk drive.

**Comment by exelix11** [comment]
interesting, afaik switch shouldn't have region differences, i personally checked 5.1 and 6.0.1 files but got the other names from the the same soruce. I'll look into this

**Comment by jaconfurz** [comment]
> interesting, afaik switch software shouldn't have regional differences, i personally checked 5.1 and 6.0.1 files but got the other names from the the same soruce. I'll look into this

Yeah. For reference, I'm running a 6.0.0 switch, with the dumped rawnand of the same version. My Qlaunch (Home menu) was inside "33dd03103f1ac6a50e13d27ce5e00b2f.nca" while my user settings applet is "2a59543bf2eced1ed352cacd2067ba48.nca"

When I do a google search on these, the forum results are almost always in Japanese, which is weird considering my switch is a western release (XAW)

**Comment by exelix11** [comment]
Ok so i've got another comfirmation from an user that 33dd works for 6.0.0, searching on google on those chinese websites most have that one but a few have the one in the guide as well, either they know what's going on or got it from my guide, still i updated the guide to include the other hash as well. About 2a59... i couldn't find anything

**Comment by exelix11** [comment]
I think it's more likely the list of hashes for 6.0 was wrong because they're the only ones that doesn't match, in fact i got the 6.0.1 hashes from another guy cause that list didn't get updated.
