### ISSUE TITLE
作者您好，我发现这个插件在switch中的的最新AMS-13.2的emuMMC中使用锁屏壁纸重启后报错

### ISSUE THREAD

**Issue by Ic-any** [exelix11/SwitchThemeInjector#107]
作者请问插件什么时候会支持13.2的固件呢？加油哦！

**Comment by exelix11** [comment]
Please use english when asking for help.

It seems you're having crashes on boot on 13.2 with emummc, there are two things to note:
- Make sure you have [latest releases](https://github.com/exelix11/SwitchThemeInjector/releases/tag/v-4.6.4) of the installer, that supports 13.2
- If you have different firmwares on sys and emu you can't use themes on both because they use the same folder on the sd card, this means one of them will always crash.

To fix your console delete the folder /atmosphere/contents/0100000000001000  from your sd, then download latest theme insaller and run it from emuMMC to install your theme.

**Comment by Ic-any** [comment]
Sorry, the first time I asked, I will pay attention next time. Thank you for your help, thank you

**Comment by Claod44** [comment]
Hello,
Same problem here on 13.2, latest hekate and Atmosphere. Latest NXThemeInstaller.nro. Crashing right after extracting home menu... No Contents folder inside atmosphere... Any idea ? :/

**Comment by exelix11** [comment]
Possibly sd corruption. Delete the themes folder from the root of your sd and try again.

**Comment by Claod44** [comment]
I just did, that's not working. And the whole SD istallation is new...
![thumbnail_IMG_6714](https://user-images.githubusercontent.com/27275808/151457028-af004641-5838-4bb2-9be3-1c33b83ee7be.jpg)

**Comment by exelix11** [comment]
Crashing title id is the system bsdsocket service, i don't know what does that mean and idk if that's related to the theme installer.
As a general homebrew advice try using title takeover instead of the album applet, that solves mysterious problems like these.

**Comment by Claod44** [comment]
You mean running a game pressing R, I did. I was not in applet mode ... That's what you mean ?

**Comment by exelix11** [comment]
> You mean running a game pressing R, I did. I was not in applet mode ... That's what you mean ?

Yes i meant that, unfortunately if that doesn't help i don't have any more suggestions.
This is the point where i'd just set up atmosphere from scratch on a different sd card to try to reproduce the problem

**Comment by Claod44** [comment]
I have others bootentries like Reinx and SXOS (those are not updated), And I don't know if themes installed previously on those firmwares are shared, and where I can delete them. That's the only thing that could create problems I think... Maybe it'll lead to a clue

**Comment by exelix11** [comment]
That's not the problem, installed themes go into the cfw-specific folder and the worst they can do is crashing on boot so i don't think that's it.

**Comment by Claod44** [comment]
It's happening right after I extract home menu, when the Themes folder is created on the root of my SD, after that each time NXThemeInstaller crashes ... Why the bsdsocket would create problems in this conditions ?

**Comment by Claod44** [comment]
Found ! At the first screen after removing SXOS folder, NXThemeInstaller is asking me what folder to use between ReiNX and Atmosphere. So It seems the error occurs with a title inside SXOS. :)

**Comment by exelix11** [comment]
To be clear, you launch latest release, get to the select cfw screen, pick atmosphere and then the console crashes after extracting the home menu. If the sxos folder is not there it doesn't happen, correct?

**Comment by exelix11** [comment]
Can you reproduce the fix on the original sd card as well ?

**Comment by Claod44** [comment]
Only Deleting sxos root folder is working. In its content I had my cheats so the whole directory tree was : sd://sxos/titles
Nothing else inside. So it seems nxthemeinstaller.nro is searching for something inside the sxos folder, and it's not here. Any idea ?

**Comment by Claod44** [comment]
> To be clear, you launch latest release, get to the select cfw screen, pick atmosphere and then the console crashes after extracting the home menu. If the sxos folder is not there it doesn't happen, correct?

Yeah, when the sxos root directory is not here, no crash.

**Comment by Claod44** [comment]
fs.hpp or some file is searching nsp, bin, dat or a file as proof of cfw installation and use. But in my case sxos folder is not containing anything, then it leads to a crash.

**Comment by exelix11** [comment]
I don't see any obvious problem in the code, will have to do some tests.
