### ISSUE TITLE
Error: Can't extract home menu version info.

### ISSUE THREAD

**Issue by FireVirusMC** [exelix11/SwitchThemeInjector#109]
If you want me to send an image just ask.

**Comment by exelix11** [comment]
Firmware version? This usually happens when your cfw install is messed up I'd day try setting up your sd from scratch.

**Comment by FireVirusMC** [comment]
I'll try it thanks. I want to keep all my games and save data. What folders should I not delete to prevent losing them?

**Comment by FireVirusMC** [comment]
So should I just delete all files related to cfw and just set up sd from there?

**Comment by Claod44** [comment]
Same error here... Extracting leads to a crash.
