### ISSUE TITLE
Upon selecting extract homemenu an error message shows up

### ISSUE THREAD

**Issue by simplyargyll** [exelix11/SwitchThemeInjector#11]
The error is as follows: "Residentmenu not found in lyt dir" i've followed every step up to this point and they all worked except for this one

**Comment by suchmememanyskill** [comment]
You probably have outdated keys, check if you have master_key_06 in your keyset file if you're on fw 6.2.0. If you don't, redump with lockpick (note that lockpick doesn't work for 6.2 keys on sx emunand)

**Comment by exelix11** [comment]
^ Yeah, also if you got the keys from the internet note that there is a webpage with some keys where it says `(not confirmed)` If you happened to have downloaded those keys remove the not confirmed ones.

**Comment by simplyargyll** [comment]
Yeah i had to delete the prod.keys and title.keys and redump, it fixed it
