### ISSUE TITLE
Error: Cannot detect the home menu version you're running. Hatcool failed to extract the home menu version info,

### ISSUE THREAD

**Issue by FireVirusMC** [exelix11/SwitchThemeInjector#110]
NxThemes Version: 2.6.4 
System Version: 13.2.1
Atmosphere Version: 1.2.6
Even after a clean install of my sd card it still doesn't work

**Comment by FireVirusMC** [comment]
*issue fixed it will extract as long its not through nsp. Use applet or hold right shoulder button while opening a game

**Comment by exelix11** [comment]
I see, nsp versions are not the same as title takeover and are not supported. 
I don't know where people find them but i only release nro builds.

**Comment by FireVirusMC** [comment]
People can convert nros to nsps nowadays.
