### ISSUE TITLE
[Suggestion] Reboot behaviour seems improper/causes crash?

### ISSUE THREAD

**Issue by monstrosities** [exelix11/SwitchThemeInjector#111]
Hello,

Just an issue I've noticed with the homebrew, when I finish installing a theme and use the application's reboot there's always a crackling noise and the console turns off or returns to RCM mode, not sure which. I don't experience this with any other homebrew application or reboot method.

I use the homebrew in title takeover mode with the latest version of Atmosphere and the latest official firmware update.

Perhaps you would consider implementing ams:bpc for a safe reboot method as other applications have done?

https://github.com/Atmosphere-NX/Atmosphere/commit/c02f32f1bf0c0b4bff15306670c0d3809849d421

Of course you can simply exit the homebrew and use something else but there are times when you forget.

Thank you!

**Comment by exelix11** [comment]
I've been using bpc to reboot for a while, see https://github.com/exelix11/SwitchThemeInjector/commit/388280ae232728e34bc398c4931786ff7e9db83b not sure why you get this behavior.

**Comment by monstrosities** [comment]
Is that the same implmentation as ams:bpc? I notice you implemented it long before the first example I'd seen in atmosphere's reboot to payload. Also please excuse my ignorance, I'm no coder.

**Comment by exelix11** [comment]
`bpcRebootSystem` is a system API that has been available in libnx for a while but it seems ams uses `spsmShutdown` to reboot instead of bpc directly, most likely that is the problem. Will try to switch to this other api and see if it works.

**Comment by monstrosities** [comment]
Just wanted to say thank you for that fix, works completely fine now.
