### ISSUE TITLE
Can you update this to work with firmware 14.0?

### ISSUE THREAD

**Issue by MewtwoFanz** [exelix11/SwitchThemeInjector#113]
Please?

**Comment by JrRadiant** [comment]
Can't wait for FW 14.0.0 support. Many thanks in advance!!!

**Comment by Ch3ck3rM0n** [comment]
Yeah, please give an update for AMS on FW 14.0 :-)

**Comment by Migushthe2nd** [comment]
Yes why does it take so long?? My thwmes are not working

**Comment by exelix11** [comment]
> Yes why does it take so long?? My thwmes are not working

No, bad migush. No themes for you

**Comment by TriceTheLegend** [comment]
update please

**Comment by maddiethecafebabe** [comment]
![image](https://user-images.githubusercontent.com/75337286/160077910-e80f387b-98a1-48f3-8d99-3eec66fa23fe.png)

**Comment by ELY3M** [comment]
for impatient guys. grab nro from my repo....   it is best to be patient and wait for release from this repo.

**Comment by exelix11** [comment]
Fyi if that's the ips I posted on discord note that it fixes the lockscreen but the all apps menu is broken, that's why I didn't upload it on github yet.

**Comment by sodasoba1** [comment]
> Fyi if that's the ips I posted on discord note that it fixes the lockscreen but the all apps menu is broken, that's why I didn't upload it on github yet.

From personal testing allapps does work without backgrounds but for most people that defeats the object, perhaps you can disable the background in the groups/folder section and add a new blank pane would that help you think?
