### ISSUE TITLE
Lockscreen Themes crash Atmosphere

### ISSUE THREAD

**Issue by migwynkriid** [exelix11/SwitchThemeInjector#123]
HOS: 15.0.0
CFW 15.0.0
Updated sigpatches
Extracted Home screen and updated the latest system patch via Theme Installer

Every Lockscreen theme crashes the Atmosphere CFW

**Comment by migwynkriid** [comment]
HOS: 15.0.0
CFW 15.0.0
Updated sigpatches
Extracted Home screen and updated the latest system patch via Theme Installer

Every Lockscreen theme crashes the Atmosphere CFW

**Comment by exelix11** [comment]
See latest release in the releases page, I just pushed 15.0 support.
