### ISSUE TITLE
Firmware 15.0 / AMS 1.4.0 crash

### ISSUE THREAD

**Issue by Ch3ck3rM0n** [exelix11/SwitchThemeInjector#124]
Hello,

after updating to newest FW15.0 with Atmosphere 1.4.0 pre-release the Theme Installer crashes to the often known 2162-0002 error.

Waiting for Support ;-)

**Comment by exelix11** [comment]
Works fine on my end, could be sd card issues.
Try deleting the themes folder from your sd card then launching the installer, it should create it with the proper settings

**Comment by BaamAlex** [comment]
Works fine here too. Installed my theme, reboot and it boots fine.

**Comment by Ch3ck3rM0n** [comment]
Okay it took me some time, but I found out you are right. It seems me lockscreen theme (https://themezer.net/themes/lockscreen/AtmoLock-461) is not longer working and causes the crash -.-

**Comment by exelix11** [comment]
Lockscreen themes need latest themes patches, the theme installer will download them automatically when you launch it.
If your console is not connected will tell you how to download manually

**Comment by Ch3ck3rM0n** [comment]
> ... is not connected will tell you how to download manually

Yeah its not connected.
Sorry this is new for me, it always worked before ^^
