### ISSUE TITLE
Support for v16.0

### ISSUE THREAD

**Issue by North-West-Wind** [exelix11/SwitchThemeInjector#127]
Atmosphere released 1.5.0 for switch 16.0.0. Right after boot (switch logo fades out), Atmosphere reports error about "0100000000001000"

**Comment by warnooob** [comment]
delete that folder for now, nxthemesinstaller will recreate the folder once the app is updated and the theme is redownloaded

**Comment by exelix11** [comment]
Support for 16.0 is now UP, just connect the theme installer to the internet and it will download the needed patches automatically. If you don't want to connect your console to the internet follow [this guide](https://github.com/exelix11/theme-patches)
