### ISSUE TITLE
An indicator that the latest patch has been downloaded and applied

### ISSUE THREAD

**Issue by bibliophilical** [exelix11/SwitchThemeInjector#130]
Thanks for the great homebrew apps dev.

I would like to request for an indicator, either a text line with .ips version number listed or a date, to be placed somewhere in the app so one can be sure their app has the latest patch that can be used with the latest firmware. This is a small request that doesnt affect the usability of the app as it is now but would be much appreciated.

**Comment by exelix11** [comment]
The installer already has this feature: on start if it recognizes you have an unsupported version of the home menu will show a different start page with the warning.

Once the fix becomes available it will also try to download it automatically and the warning page will disappear
