### ISSUE TITLE
Fonts aren't changing anymore after updating to Firmware 16.0

### ISSUE THREAD

**Issue by windystrife** [exelix11/SwitchThemeInjector#133]
Last week I updated my switch to firmware version 16.0. Before that themes and fonts both worked. I also downloaded the patches, so that it works with this version and extracted my home again. After I updated only themes kept working. Fonts would install, no errors, but after rebooting it wouldn't actually change. It's also the same font I used before updating and it's under 2mb.

**Comment by exelix11** [comment]
This is a known issue, the firmware update changed how fonts are handled and due to how atmosphere handles mitm on system titles it's not supported yet, i asked on reswitched if a fix is possible.
If this not fixable i'll have to remove support for custom fonts on newer firmwares.

**Comment by monstrosities** [comment]
I just saw that support was added for this in the upcoming atmosphere release for 16.0.3.

https://github.com/Atmosphere-NX/Atmosphere/commit/f0240db75a8913ccd3b12521640bbd03d10d6a5f

**Comment by exelix11** [comment]
Atmosphere update is out and fonts seem to work again, no need to update the theme installer

**Comment by windystrife** [comment]
thanks 👯
