### ISSUE TITLE
i cant install themes because once i do my screen turns black or the lock screen and i cannot unlock the switch

### ISSUE THREAD

**Issue by szymon420699** [exelix11/SwitchThemeInjector#135]
i cant install themes because once i do my screen turns black or the lock screen and i cannot unlock the switch

i will have to remove the 01000000001000 folder and the 1300 in the contents folder for atmosphere for it to revert to default switch layout and i cannot install any theme i tried to remove all themes install it one by one by restarting nothing helped

pls help

**Comment by exelix11** [comment]
I assume you mean it crashes ? Delete the `/themes/systemData` folder from your sd card that will force the theme installer to re-extract the resources.
Is your switch connected to the internet ? The installer automatically downloads compatibility updates, if the console is not connected you will get warnings about missing patches, you should read them carefully.

**Comment by szymon420699** [comment]
yes my switch is connected to the internet, that hasnt changed anything i still cannot use the switch unless i dont use any themes still black after the nintendo switch logo

and also its not a blue atmosphere error or my switch crashing, its once i reboot the system to apply a theme my switch becomes unusable just black i have to delete the 0100001000 folder in atmosphere for it to work again stock theme


i think the solution is to just reinstall emummc and atmosphere i will do that once i get my sd card and i will update you on that  it might com ein the next few days

**Comment by szymon420699** [comment]
yep reinstalling emummc fixed the problem
