### ISSUE TITLE
Always get error (blue atmospher page) :-(

### ISSUE THREAD

**Issue by AliQ84** [exelix11/SwitchThemeInjector#136]
Hi
I have a Lcd Nintendo Switch V 16.0.3 atmospher 1.5.3 and i wana install Custom theme. I download  NXthemeinstaller.bro  V2.7 (lastest Version) from github and download many theme pack from ThemeZer net. I can not install lock screen theme because i get blue error Atmosphere screen after rebooting... 

I read many page for this problem، that says install new Version NXtheme installer!!

Thanx for help :)

**Comment by exelix11** [comment]
Probably same as https://github.com/exelix11/SwitchThemeInjector/issues/135, check out my answer there

**Comment by AliQ84** [comment]
I had a defegger Lcd Switch that had such a problem, then I sold it and bought this one and hacked it

**Comment by AliQ84** [comment]
Is it possible to download through the switch itself to fix the problem?

**Comment by exelix11** [comment]
Connect the console to the internet and it should download the patches automatically

**Comment by AliQ84** [comment]
If connect to internet dont ban?

**Comment by AliQ84** [comment]
Dns requird?

**Comment by exelix11** [comment]
Yes you need the dns or else you'll get banned. Otherwise just download the patches using a pc

**Comment by AliQ84** [comment]
The problem was solved!!  I downloaded the Theme Patches file and Pasted it into the themes folder on SD Cart, then rebooted and installed Lock Screen Without error!  Finally the problem is solved!!

Thanx For help :)
