### ISSUE TITLE
Error when trying to install themes - dump home menu

### ISSUE THREAD

**Issue by henryzusa** [exelix11/SwitchThemeInjector#139]
Running latest Atmosphere with Switch version 16.1.0
When trying to open the Theme Injector I receive this: 

_The current firmware version is different than the one of the extracted home menu, do you want to dump the home menu again? If the extracted home menu doesn't match with the installed one themes will crash_ 

Should I hit yes? How do I solve it?

**Comment by exelix11** [comment]
You should click yes.

**Comment by henryzusa** [comment]
> You should click yes.

That helped only to open the app, but another issue arised.
I installed some themes, then upon rebooting Atmosphere crashed, so I went forward and deleted the themes folder and Atmosphere came back.
However, now the Theme Injector won't open. It crashes with an error as soon as I try to open it.

**Comment by exelix11** [comment]
Do you get any error code?

**Comment by henryzusa** [comment]
I copied the latest Theme Injector NRO on my USB. Now I could open it and install some themes, but upon rebooting, Atmosphere crashes and I have to apply the workaround of manually deleting the 0000...01000 folder for it to come back.

**Comment by Istador** [comment]
> I copied the latest Theme Injector NRO on my USB. Now I could open it and install some themes, but upon rebooting, Atmosphere crashes and I have to apply the workaround of manually deleting the 0000...01000 folder for it to come back.

@henryzusa Keep in mind that you need to copy the `systemPatches` manually if your console isn't connected to the internet:
https://github.com/exelix11/theme-patches#if-you-dont-want-to-connect-your-console-to-the-internet
