### ISSUE TITLE
not working on 16.1.0

### ISSUE THREAD

**Issue by a8ram** [exelix11/SwitchThemeInjector#140]
is there like a patch or something for it to work on 16.1.0?

**Comment by exelix11** [comment]
Afaik it works, connect the console to the internet or manually download the new patches, see https://github.com/exelix11/theme-patches

**Comment by a8ram** [comment]
> Afaik it works, connect the console to the internet or manually download the new patches, see https://github.com/exelix11/theme-patches

I connected to the internet and it worked! thank you very much
