### ISSUE TITLE
Support for Firmware 17.0.0

### ISSUE THREAD

**Issue by SquishyMp4** [exelix11/SwitchThemeInjector#141]
After updating to the new firmware and atmosphere I can no longer install themes I have downloaded. Whenever I try booting up NxThemesInstaller I get the message "error while extracting home menu: keys have not been initialized". This only started happening when I updated so I'm assuming its the firmware update.

**Comment by AntiFly** [comment]
cause u miss the new keys... cause there are no keys available yet...

**Comment by exelix11** [comment]
The theme installer extracts the keys on its own so this is an actual issue. 

Do you have an nsp launcher? Those are known to be be broken, you should launch it horn hbmenu using title takeover (or just the album)

**Comment by ELY3M** [comment]
I have same issue.  I did launched the app both ways.   it said it failed to get keys.   
I will wait for new update.

**Comment by SquishyMp4** [comment]
> The theme installer extracts the keys on its own so this is an actual issue.
> 
> Do you have an nsp launcher? Those are known to be be broken, you should launch it horn hbmenu using title takeover (or just the album)

I launched the Themes Installer from both the album and by holding R when launching a game and got the same error both times.

**Comment by IAmArique** [comment]
I am also having this issue on 17.0.0. Guess I'll wait it out as well for a future update...

**Comment by exelix11** [comment]
Release is up
