### ISSUE TITLE
can't save the themes 

### ISSUE THREAD

**Issue by windfall617** [exelix11/SwitchThemeInjector#147]
![22e349bf2b3975dff02bdbdd8944d783](https://github.com/exelix11/SwitchThemeInjector/assets/88772139/b84f5c67-3642-4e88-a243-108079255bb4)
How to continue to save the themes?
Hi,sry to boder u 
I get trouble while I save the themes. it only tells me to write the information but the theme info has no more options to save the  themes :(

**Comment by exelix11** [comment]
See https://github.com/exelix11/SwitchThemeInjector/issues/74
