### ISSUE TITLE
support for 18.0.0 (AMS 1.7.0)

### ISSUE THREAD

**Issue by SuperTechTricsX** [exelix11/SwitchThemeInjector#148]
theme installer keeps causing switch to crash on 18.0.0

**Comment by exelix11** [comment]
Other people reported it works fine. Uninstall your current theme and delete the themes folder in the root of your SD card,  then try again

**Comment by tuanzi11** [comment]
我刚才也报错了 进到主题里面显示缺少补丁
手动放一下补丁![image](https://github.com/exelix11/SwitchThemeInjector/assets/92656905/ae3d3569-e126-440d-8e63-9eff28105224)我刚才报错尾数1000    放完补丁就好了

**Comment by Maudeth** [comment]
> Other people reported it works fine. Uninstall your current theme and delete the themes folder in the root of your SD card, then try again

I went through the same process and yet Atmosphère still crashes upon reboot due to the theme installation. I guess we should expect a new update supporting 18.0.

**Comment by exelix11** [comment]
The new patches are already out, just connect the console to the internet so the theme installer can update. Or follow the guide in the prompt to update offline.

**Comment by tuanzi11** [comment]
> > Other people reported it works fine. Uninstall your current theme and delete the themes folder in the root of your SD card, then try again
> 
> 
> 
> I went through the same process and yet Atmosphère still crashes upon reboot due to the theme installation. I guess we should expect a new update supporting 18.0.

Just install the patch manually. Just replace it.

**Comment by Maudeth** [comment]
> The new patches are already out, just connect the console to the internet so the theme installer can update. Or follow the guide in the prompt to update offline.

Short after you commented, I did updated, work flawlessly as always after that.
