### ISSUE TITLE
Error code 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by Emorales72** [exelix11/SwitchThemeInjector#153]
I have a problem with firmware 18.1.0. 

In all the themes that I installed, it gives me problems when entering the console settings page. 

I have already installed the patches

![IMG_20240929_002417](https://github.com/user-attachments/assets/d4a6d72a-dc9d-4779-8404-9c7bbc87e413)

Please, help me

**Comment by exelix11** [comment]
That can be caused by multiple things.
First uninstall all themes and delete the themes/systemData folder from your SD card, that will reload the system assets needed to install themes. Then try again.

If it still happens it may be a memory issue, try applying themes without sysmodules running.

**Comment by Emorales72** [comment]
Thanks bro, it worked for me.

Maybe it was some conflict between files but now it works fine.
