### ISSUE TITLE
NXTheme No Backgrounds, and Settings Crash

### ISSUE THREAD

**Issue by FrameEnder** [exelix11/SwitchThemeInjector#18]
I'm on FW 6.2 running ReiNX 2.0, and I'm using the latest 1.2 build of NXTheme, I have all my keys dumped, and I extracted the Home Menu to be able to install 6.x theme's, but whenever I do none of the backgrounds seem to show up, I don't see a common.szs in the title folder, only the resident menu layout changes, and for whatever reason if I try to install a NXtheme to the settings it crash's the console when I try to load into the settings app.

Here are the theme's I use, IDK what else to offer to resolve this issue.

[Theme.zip](https://github.com/exelix11/SwitchThemeInjector/files/2751279/Theme.zip)

**Comment by FrameEnder** [comment]
I'm using the latest 2.0 ReiNX, running ExFat (I'm using a 128gb SD, so no Fat32 support), I just tried the test NXTheme file, but like before the background didn't change just the layout, and so you know the settings only crashes in my case when I inject Any NXtheme files related to setting themes, and yes even after rebooting it would still crash, which somehow seems to be persistent even if I "delete" the theme with the option in NXTheme Installer, only being fixed when I manually delete the lyt folder on my SD Card.

if it helps here's the [0100000000001000](https://github.com/exelix11/SwitchThemeInjector/files/2751390/0100000000001000.zip) folder, I uploaded it after injecting a full set of NXTheme's, and tested to see if the same issues showed up, and they did, so maybe it'll be of some use?

**Comment by FrameEnder** [comment]
I also took sometime to setup another SD Card with Fat32 to see if my 128gb SD Card might have been corrupting as I dunno exfat has it's issues, and I loaded up ReiNX 2.0, and Atmosphere 0.8.2, it still gave me similar issues [No Background IMG, and Settings Crashing] even when I rolled the NXTheme Installer version from from 1.2 to 1.1, and even 1.0

Here is the Atmosphere Crash Report, which should show what's at least going on with the settings app

[00486032579_0100000000001000.log](https://github.com/exelix11/SwitchThemeInjector/files/2751700/00486032579_0100000000001000.log)

Also Thread Info? Dunno just trying to supply you with ample info on whatever I find

[dumps.zip](https://github.com/exelix11/SwitchThemeInjector/files/2751706/dumps.zip)

**Comment by akaithemes** [comment]
So I checked your 01000000001000 folder and I tested it, and I crashed on the settings and got the Homescreen withouth any image, and to fix this I just deleted the folder exefs (I'm using atmosphere) and I booted again and I got the background image back to the homescreen and when I opened the settings and I didn't crash again.

You really don't need that many things inside of the 0100000000001000 (other than some files that comes with atmosphere) the rest is just space used. Try deleting that folder.

**Comment by FrameEnder** [comment]
Thank-you deleting that folder fixed the issue, I guess it's a remanence of an earlier theme patching method, or SDFiles repack, TBH I've not changed my Switch SD since the scene started, so I guess that'll happen.. I dunno why I didn't think of just emptying my entire 0100000000001000 folder surely NXTheme Installer would fill in all the required files anyway.

Thanks Again, I suppose we can close this issue now then.
