### ISSUE TITLE
No themes found

### ISSUE THREAD

**Issue by rtrman** [exelix11/SwitchThemeInjector#19]
I'm running 6.1.0 SXOS 2.5.2, Nxthemes 1.2, exFAT genuine SanDisk SD card.
I've dumped my keys, run lockpick, and dumped the NCA. However, the Themes tab suggests no themes are in the /themes folder, even though they are!
Pressing A anyways causes the app to crash.

**Comment by exelix11** [comment]
Make sure to update to the latest version of the installer and that the themes folder is called just `themes` (no capital letters)
Also using a mac could cause issues when moving files on the sd card, try using Windows or ftp.
if none of these fixes your issue I guess it's ad corruption, it happens on exfat, you should format your sd to fat32

**Comment by rtrman** [comment]
Thanks for the reply.
The folder is all lower case, the files were transferred by a Windows machine, and I have no issues with any other data, which makes me think corruption is unlikely? Perhaps it is the theme files I have, but if so, I can't understand why NXTheme is crashing.

**Comment by exelix11** [comment]
I'm not sure then, those are the most common issues, try downloading some themes from the /r/NXThemes subreddit. Just to be sure i would try using another sd card with fat32.
Also make sure the .nxtheme extension of the files is lowercase as well.
