### ISSUE TITLE
Clock cut off with "ClearLayout"

### ISSUE THREAD

**Issue by RenaKunisaki** [exelix11/SwitchThemeInjector#20]
With ClearLayout patch for home screen, the clock is too far to the left and gets partly cut off. (Time is 12:54 AM in this screenshot)

![2019011900543300-57b4628d2267231d57e0fc1078c0596d](https://user-images.githubusercontent.com/1185585/51430918-b3409a80-1bef-11e9-8d07-679aad532b39.jpg)

**Comment by suchmememanyskill** [comment]
(Creator of clearlayout here) i created the layout around the 24-hour time format. I thought that anyone could switch to it, but apparently not. Heard that disabling the battery% will centre it for the 12-hour time format. (Also note that the battery is 100%, which also makes the clock shift to the left).

This is not a bug, just a poor design choice.
