### ISSUE TITLE
Crash After Boot

### ISSUE THREAD

**Issue by Dudamax** [exelix11/SwitchThemeInjector#21]
Whenever I try to load the nro (running version 1.2) it says "Loading" then it crashes my switch giving me the error code 2168-0002.

**Comment by exelix11** [comment]
Sounds like sd corruption, do you happen to use a mac or have an exfat sd card?

**Comment by Dudamax** [comment]
No, I have have a windows pc but my sd card is exfat. Opening other homebrew apps and installing to sd works fine its just NXThemes that gives me the problem.

**Comment by exelix11** [comment]
Which cfw do you use ?
All the people who had this issue was something sd related, can you try a different sd card with fat32 ? Also fixing the archive bit with CTCaer could be worth a shot

**Comment by Dudamax** [comment]
I use Kosmos. I didn't know that Hekate could do that, I always fixed it via windows file explorer, I will try it that way and see if it works.

**Comment by adamarsx** [comment]
Having exactly the same problem, I use a Mac and used the hekate archive bit option (also tried to clear it using terminal on my mac).

**Comment by Dudamax** [comment]
None of the previous solutions work. I really down want to change to a fat 32 because of the file transfer limit.

**Comment by exelix11** [comment]
Try with another sd card, just to rule out that possibility.
