### ISSUE TITLE
lockscreen not showing

### ISSUE THREAD

**Issue by favoritul** [exelix11/SwitchThemeInjector#22]
after apply nxtheme lockscreen ,then reboot, the lockscreen not showing and cant unlock switch. cant do anything

**Comment by suchmememanyskill** [comment]
You probably installed an incorrectly made theme. You can remove it by going into the (CFW)/Titles/0100000000001000/romfs/lyt and deleting every file in that folder.

Would you mind dm'ing me the file (Such Meme, Many Skill#2921) on discord to analyse what went wrong?
