### ISSUE TITLE
No more Tranzparency

### ISSUE THREAD

**Issue by Klauserus** [exelix11/SwitchThemeInjector#23]
Hi

I had used the theme injector for switch 5.1. I choosen "two rows home" for my theme. In menue (settings for example) i have seen my custom wallpaper. Well, i have update to 7.0.1 and make a new custom theme. All good, but the transparency are lost. Have i overseen an option? I will my transparency back :)

I have used Atmosphere 8.3 at 5.1 and 8.4 on 7.1

You need more informations?

Thanx a lot for your great programm.

**Comment by exelix11** [comment]
Not sure if i understood your issue but, with latest update i changed the bg handing on lower firmwares for better compatibility, to have a background in the settings page you have to make an nxtheme that targets the settings applet

**Comment by Klauserus** [comment]
ok. my fault. i forgot the right theme to create. shame

**Comment by exelix11** [comment]
👍
