### ISSUE TITLE
Unable to theme on v7.0.1

### ISSUE THREAD

**Issue by TTTechnoPro** [exelix11/SwitchThemeInjector#24]
I have installed your NRO file. It automatically dumps my home menu. It successfully does. I close out and drop in the Reykja theme folder to /themes/Reykja. I relaunch the NRO File. It detects the folder and when I press A to open the folder, this causes Atmosphere 0.8.4 to crash and it does this no matter how many times I try. Any tips?

**Comment by TTTechnoPro** [comment]
UPDATE: I removed the Reykja folder in /themes/Reykja and copied the 6 .nxtheme files inside and put it in /themes. This causes Atmosphere to crash immediately when loading the NRO file

**Comment by TTTechnoPro** [comment]
Error Code: 2168-0002 (0x4a8)

**Comment by suchmememanyskill** [comment]
2168-0002 is a general userland crash, won't get much use out of that

Can you give some more specifics? Like if you are using a mac to copy files, or if you are using exfat or fat32.

For now let's try one thing. Boot hekate, go to tools and click "reset archive bit - all" or something like that

**Comment by TTTechnoPro** [comment]
I am using a Mac to format my SD Card to FAT32 using Disk Utility. I have tried resetting the archive bit and for all and it did not work.

**Comment by exelix11** [comment]
THis is totally the archive bit issue. Delete the themes folder, launch the theme installer and let it create it and extract the home menu, then transfer themes through ftp. It should work.

**Comment by TTTechnoPro** [comment]
It worked, thank you.
