### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by leo60228** [exelix11/SwitchThemeInjector#25]
As you have linked with GPL2 code (mbedtls), this is presumably GPL2, but it is unclear.

**Comment by designgears** [comment]
https://choosealicense.com/no-permission/

**Comment by noirscape** [comment]
Mbedtls is Apache 2.0, not gplv2

**Comment by leo60228** [comment]
@designgears mbedtls has multiple licenses. The one in the repo is GPLv2.

**Comment by exelix11** [comment]
By mistake i included the wrong license, the repo from where i got the code from uses [apache 2.0](https://github.com/ARMmbed/mbedtls/blob/development/LICENSE).
This repo is gplv2 licensed.
