### ISSUE TITLE
Home Menu won't extract

### ISSUE THREAD

**Issue by CecilFF4** [exelix11/SwitchThemeInjector#26]
I was on FW 6.2.0 and successively dumped the home menu at that point (so, yes, I had the prod keys at the time including key 06). But, before installing themes, I decided I wanted to update to 7.0.1. Figured I'd do that, then redump the keys (using lockpick) and home menu. Problem is that the home menu won't re-extract. I deleted the old extraction of them, redumped the keys (they are identical to the old except the new keys file includes a few bis keys, and tried to dump the home menu. Fails every time with the message "residentmenu not found in lyt dir". I've googled that error and it said I got a bad key or something, which is untrue; again, the keys worked before when I did this on 6.2.0 and they haven't changed except for the addition of the bis keys.

Lockpick 1.2.1
NXThemesInstaller 1.2
Atmosphere 0.8.4

**Comment by suchmememanyskill** [comment]
Seems like you have an older version of the nxtheme installer, can you try the latest version? (Latest is 1.3)

**Comment by CecilFF4** [comment]
You are absolutely correct. I updated it, it extracted the home menu, then installed my selected theme. I thought it was on the latest version. Thank you for pointing that out.
