### ISSUE TITLE
Dot file cause crash

### ISSUE THREAD

**Issue by PhanVietTrung** [exelix11/SwitchThemeInjector#29]

**Comment by PhanVietTrung** [comment]
When copy theme file from MAC, it auto create hidden ._ files, cause crash, it seems NXTheme try to read those file (with same ._XXX.nxtheme extension).
Please check and ignore ._file

**Comment by exelix11** [comment]
It's not the hidden files, for some reason mac os always enables the archivd bit on external sd cards and the switch fat driver doesn't like it. This affects any homebrew and ecen system apps, i can't do anything to fix it. You can workaround it by clearing the archive bit every time you copy files or using ftp,check out this thread: https://gbatemp.net/threads/how-to-fix-archive-bit-for-all-sd-files-and-folders.515258/
