### ISSUE TITLE
No All Software Option

### ISSUE THREAD

**Issue by rjurok16** [exelix11/SwitchThemeInjector#30]
Hi Developer(s), 
I
 love it. However, my games are being cutout from the home menu and I cannot seem to find the All Software button on it. I am on 6.2.0. Is there a fix to this? Thank you!

Talk soon! :)

**Comment by exelix11** [comment]
That's because you don't have enough titles installed, the all software buttons appears when you have more than 12 games.
If you do have more than 12 games and have this issue with just one or a few themes they could be hiding it and that's up to the theme author.

**Comment by rjurok16** [comment]
Oh, I see.Thank you so much!
