### ISSUE TITLE
Theme partially incompatible with 8.0.0

### ISSUE THREAD

**Issue by YuliaS11** [exelix11/SwitchThemeInjector#31]
8.0.0 modified the home menu quite a bit and current themes have a tendency of getting stuck on a specific app using the dpad or the joy stick. Touch screen is working fine.

**Comment by exelix11** [comment]
We're working on a fix, hopefully without having to edit already existing themes.
This seems to happen only with some custom layouts, themes with just a bg image still work properly.

**Comment by exelix11** [comment]
This has been fixed with latest release
