### ISSUE TITLE
Add Theme Installer version check

### ISSUE THREAD

**Issue by Migushthe2nd** [exelix11/SwitchThemeInjector#35]
Add a theme installer minimum version entry to the json when diffing. 
The ThemeInjector, Layout Editor and ThemeInstaller should request the user to update the tool upon installing the NXTheme or when applying a diff.

**Comment by exelix11** [comment]
There's already, it links the nxtheme with the injector version that created it and describes the available features. It's part of the internal metadata of nxtheme and transparent to the user.

**Comment by Migushthe2nd** [comment]
Ah there's no version in a json, so I thought it wasn't implemented. My bad.
