### ISSUE TITLE
Move panels to front/back

### ISSUE THREAD

**Issue by Migushthe2nd** [exelix11/SwitchThemeInjector#37]
Add an option (that doesn't have to be supported by the differ) to move a panel to the beginning or end of the bflyt file. 
>The eshop's N_Tip is placed before the other items in the bflyt, which means the text is displayed behind everything. This is probably a mistake made by someone at Nintendo, since changing the panel orders doesn't change anything (no glitching and stuff). Could an option be added to the json to move the N_Tip after the rest of the panels in the RdtBtnShop.bflyt? I've had trouble with this before, but thought it wasn't that important and I 'd just remove the text or make it a legacy release

**Comment by exelix11** [comment]
Added with c6d80a882044649e8d6c1083778fdf46128ccce7.
Each `LayoutFilePatch` block in the json now has `PushBackPanes` and `PullFrontPanes` string arrays to change the order of panes. Panes won't be moved out of their parent.
