### ISSUE TITLE
dont work at emuMMC

### ISSUE THREAD

**Issue by AlpGoXd** [exelix11/SwitchThemeInjector#40]
well it do not extraxt homemenu and icant load themes please help

**Comment by exelix11** [comment]
Which firmware are you running ? Are you using latest version of the installer ?
About 9.0 currently lockscreen themes are broken, other parts should run fine

**Comment by AlpGoXd** [comment]
firmware:9.0 atmosphere version 9.4 i dumpedall keys but program dosent see the keys

**Comment by exelix11** [comment]
Sounds like you're following an outdated guide , keys are not needed anymore, download latest version of the installer and the injector.
To extract the home menu just run once the installer and it will copy all the szs files to /themes/systemData on your sd. Note that you don't actually need to use szs files as you can generate nxtheme files directly with the injector or the [web app](http://exelix11.github.io/SwitchThemeInjector/v2).

**Comment by AlpGoXd** [comment]
Ok now it works
