### ISSUE TITLE
User Page doesn't change

### ISSUE THREAD

**Issue by Xyphoseos** [exelix11/SwitchThemeInjector#43]
Hello, I recently updated my switch to 9.1.0 and before I deleted my theme in case of incompatibility.
Now I reinstall my theme but the user page doesn't change. Any idea ? All others pages/images are changed.

**Comment by exelix11** [comment]
Can't reproduce the issue, user page works fine on 9.1.0 for me. Are you using latest atmosphere, hekate and theme installer ?

**Comment by Xyphoseos** [comment]
I don't use hekate, latest atmosphère directly, and yes I use the latest nxtheme version

**Comment by exelix11** [comment]
Do you happen to use some extra modifications on top of atmosphere such as incognito or less known sysmodules ? I'd say try using a fresh install of atmosphere.

**Comment by Xyphoseos** [comment]
I use additionaly sys audio player
Nothing more
