### ISSUE TITLE
Allow users to customize the contextual Options, Start, Ok, Back buttons.

### ISSUE THREAD

**Issue by afxwinter** [exelix11/SwitchThemeInjector#45]
There currently doesn't seem to be a way to access the context sensitive buttons at the very bottom right of the switch menus.  It would be nice to be able to customize their colors instead of simply using the default light or dark theme colors built into the Switch.

**Comment by exelix11** [comment]
Those should be part of the common.szs file, you can add a common layout to a home menu nxtheme to edit them.

**Comment by afxwinter** [comment]
I've been searching through the common.szs.  Is there any documentation?

**Comment by exelix11** [comment]
I don't think so, afaik common.szs has mostly been used to remove the white line at the bottom of the home menu.

**Comment by afxwinter** [comment]
Thanks Exelix11 and thanks for all great app!  I'll close this and hunt through each module to try to find those buttons.
