### ISSUE TITLE
PNG on Player Select page

### ISSUE THREAD

**Issue by chronoss09** [exelix11/SwitchThemeInjector#47]
Hi !

I think you must add a PNG pic on Player page, for some raison, with "Transparant Playerselect 90% Scale", we can't make a JPG file, it compress the picture and its not good. with PNG, we can a Transparant backgroung and it will be good.

Sory for my english :(

**Comment by exelix11** [comment]
For that you'll have to manually convert the png to dds. Use Dxt1 with alpha compression. (Only Dxt1 is supported)

It used to convert it automatically but the converter has been removed in latest release for compatibility with 32 bit versions of windows and linux

**Comment by chronoss09** [comment]
I have W64b

**Comment by chronoss09** [comment]
Thanks, i use this http://www.easy2convert.com/png2dds/ and it work :+1:
