### ISSUE TITLE
We need new version for 10.0.1

### ISSUE THREAD

**Issue by PASTO666** [exelix11/SwitchThemeInjector#48]
As title says.. the old 2.3 app works but so much warnings..

**Comment by exelix11** [comment]
Will come in the next few days but Home menu wasn't updated so it's not high proprity, there's nothing to fix.

**Comment by PASTO666** [comment]
Thx for the quick reply.. yea i know it still works, its the warning it gives now when we try to change theme.. thx again :)

**Comment by exelix11** [comment]
https://github.com/exelix11/SwitchThemeInjector/releases/tag/v-4.4-1
