### ISSUE TITLE
ReiNX no longer uses 'titles', uses 'contents' 

### ISSUE THREAD

**Issue by KilimIG** [exelix11/SwitchThemeInjector#50]
title is self explanatory, when changing themes with the new ReiNX theme data is moved to ReiNX/titles instead of ReiNX/contents

fix pls ill do anythgn

**Comment by MiniGrief** [comment]
Untill this gets fixed, you can install themes like normal and just copy the folders from ReiNX/titles into ReiNX/contents.

**Comment by exelix11** [comment]
Updated the [current release](https://github.com/exelix11/SwitchThemeInjector/releases/tag/v-4.4-2) with a fix for this. 
It will be officially part of the next release changelog.
