### ISSUE TITLE
Crashing when Extracting Home Menu 

### ISSUE THREAD

**Issue by axisnsin** [exelix11/SwitchThemeInjector#51]
I’m on Firmware 10.0.3
Atmosphere 0.12.0-master
Every time I open the theme installer it asks me to extract the home menu and I do but when it starts it crashes
Error code 1266-0002 (0x4a8)

**Comment by axisnsin** [comment]
![image](https://user-images.githubusercontent.com/66151397/83318234-c199c000-a200-11ea-9833-c014e7bfd83a.jpg)

**Comment by axisnsin** [comment]
I have the latest version of This app

**Comment by exelix11** [comment]
Sounds like archive bit issue or sd corruption. Delete the themes folder and launch the installer, it should work.

If you use a mac avoid copying files directly and use ftp to move files around.

**Comment by axisnsin** [comment]
I did it and still no go.... y crashed to the same screen again when extracting

**Comment by exelix11** [comment]
Not sure what to say, i'm pretty confident it's some kind of sd corruption or the sdcard is just dying. I'd say format it to Fat32 and try again.

**Comment by exelix11** [comment]
[Latest release](https://github.com/exelix11/SwitchThemeInjector/releases/latest) should hopefully fix this
