### ISSUE TITLE
cannot complie the SwitchThemesNX 

### ISSUE THREAD

**Issue by tiansongyu** [exelix11/SwitchThemeInjector#55]
when i try to complie the switchThemesNx there are some error .
```
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::NxThemeGetBgImage()':
BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x1d8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.cpp:(.text._ZN7NxEntry17NxThemeGetBgImageEv[_ZN7NxEntry17NxThemeGetBgImageEv]+0x2e8): undefined reference to `DDSConv::GetError[abi:cxx11]()'
/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.1.0/../../../../aarch64-none-elf/bin/ld: BaseEntry.o: in function `NxEntry::DoInstall(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
BaseEntry.cpp:(.text._ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7NxEntry9DoInstallEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1bb8): undefined reference to `DDSConv::ImageToDDS(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool, int, int)'
```
what should i do can solve the problem .
i thought devkitpro version have too high level .
what the version of devkitpro when you complie and link the code .

**Comment by exelix11** [comment]
Mh not sure what's going on here, maybe there's some build artifact messing up stuff, try doing a make clean first. Then enter libs and launch make in both mbedtls and hactool. Hopefully after that should build, I think I'm building with latest devkitA64 so that  shouldn't be a problem.

Note that if you're building for 10.1.0 support it won't work cause I haven't made a patch for it yet.

**Comment by tiansongyu** [comment]
thanks a lot Thank you !!

**Comment by tiansongyu** [comment]
I'm building for 10.1.0 support it  .but I don't know how to downgrade it . can you tell me ?

**Comment by tiansongyu** [comment]
sir !!! I found a amazing thing !!!!   [https://wii.leseratte10.de/devkitPro/](url)   if someone use the older version devkitA64 .
you can give it to him!!!   this guy have the Collection of old devkitPro versions. Ithink this guy is the one who collect this things !!!!

**Comment by exelix11** [comment]
Don't get what you're trying to do here, the installer should build fine with latest toolchain. 
> I'm building for 10.1.0 support it  .but I don't know how to downgrade it .
Downgrade what? 10.1.0 won't be fully supported until someone (most likely me) makes a 10.1.0 patch for the lockscreen, aside from that all the other parts should work fine.

**Comment by tiansongyu** [comment]
I get it .Thank you :)
