### ISSUE TITLE
Reboot to Payload not working

### ISSUE THREAD

**Issue by neo305** [exelix11/SwitchThemeInjector#66]
When I change themes and select reboot it goes to sysnand and not CFW. I’m on emuMMC fully updated freshly and if I select reboot to payload in hbmenu and Hekate it works but not NxThemes

**Comment by exelix11** [comment]
I changed the behavior with latest update to use HOS reboot function, in theory atmosphere should hook that and perform a reboot to payload but you're not the first one who reported it's not working, i think it's some configuration in atmosphere but not sure. Will look into it.

**Comment by exelix11** [comment]
is ams can be configured to reboot to payload on regular reboot by setting `power_menu_reboot_function = str!payload` in /atmosphere/config/system_settings.ini, this is the default value if that file doesn't exist.
Can you try updating atmosphere to the latest version ?

**Comment by neo305** [comment]
Thanks but I have spent 2 days updating everything. So I am up to date on everything.

**Comment by pitrako** [comment]
I have similar problem, I'm on sysnand without emunand and reboot option from hardware button works but not in switchthemeinjector.

**Comment by BeckysFootSlave** [comment]
> is ams can be configured to reboot to payload on regular reboot by setting `power_menu_reboot_function = str!payload` in /atmosphere/config/system_settings.ini, this is the default value if that file doesn't exist. Can you try updating atmosphere to the latest version ?

Hello exelix11,

I set many things up in the "System_settings.ini" from atmosphere!
One of them is exactly what you described!
power_menu_reboot_function = str!payload

But if I use the reboot button on nx theme installer I will always be booted into OFW :(
Don't know what's happening there!

Would be awesome if you could look into this!

Greetings from Germany

**Comment by exelix11** [comment]
I think this has been figured out on discord, iirc NSP versions cause this issue. Do you happen to use one as well ?

**Comment by BeckysFootSlave** [comment]
I hope I understand you!

Yes I use nsp because of memory in applet mode!
And you mean better to start game with R-button pressed to open the nro in hbl, is that right?

Hope I got it right :)

**Comment by exelix11** [comment]
Yes, i don't distribute nsp versions so any you find around are not from me and not supported, the reason is that they're known to cause all sorts of issues like this.
Always use title takeover instead.

**Comment by BeckysFootSlave** [comment]
Dear exelix11,

You made my day!
Thank you so much for your precious time!
Thank you!

It's like the nsp maker is putting the nro into a other "folder" in memory and that's the reason why the path is completly messed up!
I did it myself with SAK for myself!

Greetings from Germany
Have a great weekend

**Comment by exelix11** [comment]
Ok i guess. 

For future reference, in case of issues please try with the nro build before opening an issue just to be sure.

I think this can be closed now.
