### ISSUE TITLE
Setting Page doesn't change

### ISSUE THREAD

**Issue by mywifebeautiful** [exelix11/SwitchThemeInjector#69]
An error occurred while changing the Settings screen.
Error while installing this theme: vector；；-M- range；-check；n(which s 2559288)» this size （）（whi
![97eb4f4579fd5ffe790428fbe675451](https://user-images.githubusercontent.com/40749916/99147849-18b42400-26bf-11eb-99f0-0938b75bc230.jpg)
ch  is 2559288)

**Comment by exelix11** [comment]
Looks like a bad theme, can you send a link to it?

**Comment by mywifebeautiful** [comment]
The theme files are available, and this error occurs with all of my theme files
[Xenwin.zip](https://github.com/exelix11/SwitchThemeInjector/files/5540777/Xenwin.zip)
This is one of them

**Comment by exelix11** [comment]
Can't reproduce, they install fine, possibly SD corruption ? Download latest release of the theme installer, copy the files again to your sd card then extract the home menu again from the theme installer option and try again.

**Comment by mywifebeautiful** [comment]
You are right,extract the home menu,issue was settled
