### ISSUE TITLE
This is not a valid theme file

### ISSUE THREAD

**Issue by CVFireDragon** [exelix11/SwitchThemeInjector#7]
I keep getting this error with every 6.0.0 szs I use except entrance.szs and residentmenu.szs. I dumped them myself btw. I can send you my dump on discord if you want

**Comment by exelix11** [comment]
Not all szs are supported, with the current version on 6.0 the following are supported: Notification.szs, Set.szs, Flaunch.szs , ResidentMenu.szs, Entrance.szs and MyPage.szs. 
I may add support for more parts in the future, the patch list is automatically generated so it always shows all the supported files, you can read it [here](https://exelix11.github.io/SwitchThemeInjector/) or in the main tab of the pc injector

**Comment by CVFireDragon** [comment]
I'm trying to make themes with Set.szs, Flaunch.szs and Notification.szs

**Comment by exelix11** [comment]
Make sure you're using latest version, if you are dm me on discord

**Comment by CVFireDragon** [comment]
Looks like it was corrupted
