### ISSUE TITLE
NXThemeInstaller 2.5.1 instead 2.6

### ISSUE THREAD

**Issue by Vbulochkin** [exelix11/SwitchThemeInjector#72]
Didn't find new installer in latest release, still no support for 11.0.0

**Comment by Vbulochkin** [comment]
I mean NXThemeInstaller, sry for that mistake

**Comment by exelix11** [comment]
Are you sure ? Did you open the [right page](https://github.com/exelix11/SwitchThemeInjector/releases/tag/v-4.6) can't test rn but with an hex editor i can see the correct version and commit in the release file

**Comment by Vbulochkin** [comment]
Yep, I tried 2 times (latest release tag was on post), homebrew detects app version as 2.5.1, app still warns that my version of OS higher than 1.0.2.0 and atmosphere doesn't boot after applying custom theme.

**Comment by exelix11** [comment]
Just tested on console, it's definitely the right version for me. Could you have multiple versions on your SD ? If you're using the homebrew appstore the update may not be live yet there. This [direct link from github](https://github.com/exelix11/SwitchThemeInjector/releases/download/v-4.6/NXThemesInstaller.nro) is 100% the right version.

**Comment by Vbulochkin** [comment]
Ok, I figured what's wrong, I have multiple versions in different folders. Sorry.

**Comment by Vbulochkin** [comment]
Thank you for help
