### ISSUE TITLE
Old layouts don't appear to hide the NSO button

### ISSUE THREAD

**Issue by j-james** [exelix11/SwitchThemeInjector#75]
Atmosphere 0.16.1, OFW 11.0.1. The layout in question is attached.

I downloaded this theme several months ago, so I'm pretty certain it hasn't been updated to include the NSO button. 

[Misty.zip](https://github.com/exelix11/SwitchThemeInjector/files/5700134/Misty.zip)

**Comment by exelix11** [comment]
The nxtheme you posted only has a background image and doesn't set any custom layout for the home menu so the default one for your firmware is not modified. If you want a layout without that button you'll have to make one yourself, i'll consider adding an option in the theme installer to always remove it regardless of layouts.

**Comment by j-james** [comment]
Ah, thank you, that's my mistake then. I'll look into editing that home menu theme.
