### ISSUE TITLE
Unable to access themezer

### ISSUE THREAD

**Issue by seanbperiod** [exelix11/SwitchThemeInjector#77]
Using 11.0 on SX 3.1 and able to connect to the internet fine. 

Whenever I load Download themes from the Internet, either random or new, I get:

There was an error processing the request, make sure you are connected to the internet and try again in a bit, itf it still doesn't work it's possible that the selected provider doesn't support this option. 

Error message:
SSL connect error

**Comment by exelix11** [comment]
Could you try if the same happens with [themezer-nx](https://github.com/suchmememanyskill/themezer-nx/releases) ? 
While working on the online features some people reported this issue as well but then nobody mentioned it anymore, i believe it has to do with sxos and/or incognito.
I'll be doing some research but unfortunately can't reproduce it.

**Comment by exelix11** [comment]
Checking themezer-nx's issues there's one that is probably related https://github.com/suchmememanyskill/themezer-nx/issues/2, an user claims it has to do with sx's "stealth mode".

**Comment by seanbperiod** [comment]
Ah yes, it was stealth mode. Thanks for the quick response!
