### ISSUE TITLE
Incompatible with Layout Editor 1.0 Beta 12 .json

### ISSUE THREAD

**Issue by Ammako** [exelix11/SwitchThemeInjector#79]
I'm extracting ResidentMenu.szs from 11.0.1, editing it in Layout Editor 1.0 Beta 12, and exporting a .json of my changes so I can use it in Theme Injector to create a theme.

Attempting to open the .json I've exported from Layout Editor throws an error.

[test.json.txt](https://github.com/exelix11/SwitchThemeInjector/files/5759758/test.json.txt)

Theme Injector expects a format like this `"Position": {"X": 30.0, "Y": -1.0, "Z": 0.0}, "Scale": {"X": 0.90, "Y": 0.90}`, but Layout Editor exports in a format like this: `"Position":"0;-218;0","Scale":"1;0.75"`

Either Layout Editor should output in a format that the latest Theme Injector understands, or Theme Injector should be made to understand the format that the latest Layout Editor outputs.

**Comment by exelix11** [comment]
I've pushed yesterday a fix on the layout editor repo, will probably release it today.

**Comment by exelix11** [comment]
[Layout editor beta 13](https://github.com/FuryBaguette/SwitchLayoutEditor/releases/latest) is out which fixes this issue.
