### ISSUE TITLE
Couldn't find any cfw folder - ReiNX

### ISSUE THREAD

**Issue by H3X1C** [exelix11/SwitchThemeInjector#8]
Hi , when opening nxThemes via the homebrew menu i'm seeing the message
"Couldn't find any cfw folder, if your cfw isn't supported open an issue on the Github"
So here i am, i'm running reiNX 2.0 on firmware 6.0.0
https://github.com/Reisyukaku/ReiNX

**Comment by exelix11** [comment]
Well, ReiNx is supported tho. Make sure you have a folder called reinx in the root of your sd, that's how the cfw is detected

**Comment by H3X1C** [comment]
How weird, as this is my sd card contents, I'll try reinstalling reinx I guess. Thanks for the quick response must be an issue on my end.
![image](https://user-images.githubusercontent.com/42491989/50540549-c41b6480-0b8b-11e9-83bb-5a8df3c1697d.png)

**Comment by exelix11** [comment]
rename it to `reinx` all lowercase

**Comment by H3X1C** [comment]
Tried that and the issue still persists, gonna reformat my SD card to see if that resolves it.

**Comment by H3X1C** [comment]
Formatting did the trick, must have been a bad SD card. Thanks for the help.
