### ISSUE TITLE
Custom Lock Screen Crashes Switch

### ISSUE THREAD

**Issue by AkeylTheOnlyOne** [exelix11/SwitchThemeInjector#80]
It gives the error code 2162-0002 (0x4a2) and every other part of the custom switch theme works.

The theme I'm using is the[ Nintendo Atmosphere Minimal mod](https://themezer.net/packs/Nintendo-Atmosphere-Minimal-mod-v5.1-24), but it happens with every other theme I use as well.

I'm using AMS 0.17.1 and the latest Switch version.

**Comment by exelix11** [comment]
Are you using latest version of the theme installer ? Lockscren needs to be patched to work and when you update the firmware you usually need to download latest theme installer to get the new patches, they're automaticallly installed once your run it.

**Comment by AkeylTheOnlyOne** [comment]
I'm using the latest version of the theme installer (2.6 I believe), but how would you go about patching the Lockscreen?

**Comment by exelix11** [comment]
The installer should automatically extract the needed files to /atmosphere/exefs_patches/NxThemesInstaller. Maybe your sd is corrupted, try deleting that folder, reboot and launch the theme installer again, it will automatically create it and copy the files again.

**Comment by AkeylTheOnlyOne** [comment]
It still crashed with the same error.

**Comment by exelix11** [comment]
If you check that folder in your sd card how many files are there ? There should be 6.
If there's less you're using an old version of the installer otherwise try extracting the home menu again it could be corruption in the systemData folder.

**Comment by AkeylTheOnlyOne** [comment]
There are 6 .ips files and 1 ver.txt file. The ver.txt file just says 6.

**Comment by exelix11** [comment]
Ok it means it's the latest version, guess at this point uninstall any theme, try fixing the archive bit from hekate, then extract the home menu again and install a lockscreen theme. If after that it still crashes i don't know, it would mean it's a bad theme (unlikely cause you mentioned trying multiple ones) or there's something preventing atmosphere from loading the ips patches.

**Comment by AkeylTheOnlyOne** [comment]
For clarification, how would I go about extracting the home menu?

**Comment by exelix11** [comment]
It's an option in the theme installer

**Comment by AkeylTheOnlyOne** [comment]
Boy do I feel dumb. It works now!

**Comment by exelix11** [comment]
👍
