### ISSUE TITLE
Possibility to spoof status indicators

### ISSUE THREAD

**Issue by meganukebmp** [exelix11/SwitchThemeInjector#81]
Hey, I've been working quite in depth with changing the layouts for various rarely themed elements like the battery and clock. The clock is arbitrarily simple to change to any value for testing but not so with the battery. In any case could spoofing the information for battery, time, parental locks an whatever else be possible? You're already MITMing qlaunch so it doesnt seem unrealistic.

**Comment by exelix11** [comment]
Uhm i don't think i understand what you want. Spoofing as in changing the values ? What would be the point showing the wrong battery % ?
If you mean removing those UI components you can move them out of the view with the layout editor.

**Comment by meganukebmp** [comment]
> Uhm i don't think i understand what you want. Spoofing as in changing the values ? What would be the point showing the wrong battery % ?
That's exactly what I mean yes. I'm modifying the assets used by the battery bar, clock (fonts) and signal. I'd like to be able to test these components without sitting there charging my device up and down or moving closer and farther from an access point. Having some sort of theme "developer mode" where I can fake information to qlaunch to test themes would be amazing.

**Comment by exelix11** [comment]
I see, unfortunately themes don't really mitm anything but just replace content in the home menu romfs so this is kinda out of scope. Not sure how to fake the battery % by replacing some service and i fear that may cause some side effects. Qlaunch could be modded to show a different value but it's not trivial and I'm not doing any qlaunch re currently so I'm not going to do it, at least for now.

**Comment by meganukebmp** [comment]
> I see, unfortunately themes don't really mitm anything but just replace content in the home menu romfs so this is kinda out of scope. Not sure how to fake the battery % by replacing some service and i fear that may cause some side effects. Qlaunch could be modded to show a different value but it's not trivial and I'm not doing any qlaunch re currently so I'm not going to do it, at least for now.

I dont want the themes themselves to spoof the values, I was suggesting the theme injector homebrew be able to do that, which you touched up in the latter part.

**Comment by exelix11** [comment]
I get what you mean, the point of my answer is that nothing in the themes tools goes anywhere near the kind of modding you'd need to do to achieve that.
The way you phrased your first question makes it sound like it would be an easy addition, it is not.
Realistically i don't think i'm ever going to do this because it really sounds complicated and it's something so specific i higly doubt i'll ever stumble upon the possibility of doing it while implementing some other feature, not to mention it's all just for a minor UI element. I might as well just close this.
