### ISSUE TITLE
Colored applet icons

### ISSUE THREAD

**Issue by Ammako** [exelix11/SwitchThemeInjector#82]
It would be quite nice to be able to use colored custom applet icons, instead of being restricted to white ones. Are there any technical limitations that would prevent this?

**Comment by exelix11** [comment]
If i remember correctly the image format used to store the applet icons supports only one channel so the color must be set via the layout.
I don't know if it's possible to change the format, i think i tried at some point but wasn't successful, guess if someone manages to do it i will try to add support for that.

Oh another thing worth mentioning is memory usage, using full color images for all icons could cause crashes but that's just speculation.

**Comment by Ammako** [comment]
I'm not sure where to change the color, in the layout. But then if I'm replacing the icon and not touching the colors, shouldn't it at least retain the original color of that applet's button? Replacing the Album icon with a custom one leaves it white, and it would be nice if it could at least keep the blue color. Though it would be nice if I could just set a different color in the layout too, but I couldn't figure out where the color is defined.

**Comment by exelix11** [comment]
The color is set to white with an implicit layout cause that's usually the preferred behavior.
In the layouts folser you can find an example layout that sets all the applet buttons to red, you can edit that to any color and merge it to your existing layout.

**Comment by Ammako** [comment]
Oh, cool. Didn't realize that was there.

One thing, though. It's very subtle, but for instance the Album button has a blue glow when you press it. Can that color be edited in the layout?

**Comment by exelix11** [comment]
Possibly but i don't know how, guess you'll have to try and figure it out on your own.
