### ISSUE TITLE
"Error - Opening file"

### ISSUE THREAD

**Issue by Zero9887** [exelix11/SwitchThemeInjector#84]
I downloaded a few themes off of Themezer and I put it on my SD card (FAT32) and when I went to go install it, it's telling me that theres an error. It says try removing the archive bit from the themes folder, so I deleted the themes that weren't working and copied them back in there but I still get the same message.

**Comment by exelix11** [comment]
This is a very generic explaination. Are you sure the files themselves are not corrupted ? Maybe they have weird characters in the name ?

**Comment by Zero9887** [comment]
I can check it out if it has any weird characters. When loading NXTheme Installer I am prompted with the message of "Error - Opening File." I got the files directly from Themezer so I wouldn't think they'd give out themes that are corrupted

**Comment by exelix11** [comment]
First thing, are we talking about .nxtheme files right ? 

> When loading NXTheme Installer

Do you mean you get the error *as soon* as you open the installer ? Like in the main manu you see the file names with an error next to them ? Can you provide a screenshot ?

> so I wouldn't think they'd give out themes that are corrupted

No but could happen in the process of moving them from and to the sd

**Comment by Zero9887** [comment]
Yes. .nxtheme files. Also checked the files and I didn't find anything wrong with the characters. I will provide a screen shot soon. Also yes right when I enter NXTheme Installer I get the error for the individual themes that don't work.

**Comment by Zero9887** [comment]
![image0](https://user-images.githubusercontent.com/82351112/114431440-589b0c80-9b74-11eb-8c40-b941d0b0114d.jpg)

**Comment by Zero9887** [comment]
never mind, i found the issue. The e on "Pokemon" had an accent on it which wasnt readable by the app. Thanks for the help!

**Comment by exelix11** [comment]
Uh right, i should probably look into adding support for that.
