### ISSUE TITLE
key extraction from FS failed (solved)

### ISSUE THREAD

**Issue by benevido** [exelix11/SwitchThemeInjector#87]
Hi,
My switch run with ams 0.19.3 and boot from hekate5.5.6 with sigpatches (fss0 boot) and I have this :  
"key extraction from FS failed" "Error while extracting ..."
Don't know how to solve this problem ?

**Comment by exelix11** [comment]
I have no clue about this one, it failed to find the required keys in the FS binary, that is part of lockpick's original source.
Which firmware are you running? Is it a regular retail one?

**Comment by benevido** [comment]
I'm on Nintendo firmware 12.0.2

**Comment by exelix11** [comment]
No, it should extract them on its own and that's what's failing. I can confirm it works fine on latest firmware so i assume it's something on your console. I'd say try with a different sd card and a fresh copy of atmosphere.

**Comment by benevido** [comment]
I think it's because I use a mod of hekate.
